source 'https://rubygems.org'

gem 'rake'
gem 'puma'
gem 'sinatra'
gem 'json'
gem 'compass'
gem 'sass'
gem 'slim'
gem 'sinatra-contrib'
gem 'sinatra-support'
gem 'sinatra-assetpack'
gem 'require_all'
gem 'httparty'
